apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  labels:
    app: minipaint
    namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: minipaint
  template:
    metadata:
      labels:
        app: minipaint
    spec:
      containers:
      - image: sahlmady/minipaint:latest
        imagePullPolicy: Always
        name: minipaint
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 50%
        
---
apiVersion: v1
kind: Service
metadata:
  name: minipaint
  labels:
    app: minipaint
spec:
  type: LoadBalancer
  selector:
    app: minipaint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80